# https://mochajs.org/#command-line-usage
# https://github.com/mochajs/mocha/tree/master/example/config

extension:
  - ts
recursive: true
require:
  - ts-node/register # replace with ts-node/register/transpile-only if you have custom types
  - source-map-support/register
bail: true
color: true
full-trace: true
reporter: spec
spec: test/**/*.spec.ts
