# https://mochajs.org/#command-line-usage
# https://github.com/mochajs/mocha/tree/master/example/config

extension:
  - ts
recursive: true
loader: ts-node/esm
require:
  - source-map-support/register
bail: false
color: true
full-trace: false
reporter: spec
spec: test/**/*.spec.ts
