name: Build and test.
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: "tests"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm test

      - uses: coverallsapp/github-action@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: "./coverage/lcov.info"
